on:
  push:
   branches:
      - master




jobs:
  build:
    runs-on: ubuntu_latest
       

    steps:
      - name: " testing"
        run: pwd
      - name: "testing printing"  
        run: echo hello





