name: Test Workflow

on:
  push:
    branches:
      - new-master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username ${{secrets.USER_NAME}} --password ${{secrets.DOCKER_TOKEN}}
      - name: building docker image
        run: docker build -t ${{secrets.USER_NAME}}/fatmamohammed2023040364

      - name: "pushing to ducker hub"  
        run: docker build -t ${{secrets.USER_NAME}}/fatmamohammed2023040364
        

    
      





